# デフォルト環境（開発）
# 開発環境: docker-compose -f docker-compose.dev.yml up
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # 開発環境用
    image: word-wise-frontend
    container_name: wordwise-frontend-dev
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # 開発環境用
    image: word-wise-backend
    container_name: wordwise-backend-dev
    env_file:
      - ./backend/.env.development
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/poetry.lock:/app/poetry.lock
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app

  # dictionary_builder:
  #   build:
  #     context: ./dictionary_builder
  #     dockerfile: Dockerfile
  #   container_name: dictionary-builder-script
  #   env_file:
  #     - ./dictionary_builder/.env
  #   volumes:
  #     - ./dictionary_builder/data:/app/data
